### ISSUE TITLE
Error for all attempts at putting data in slack...

### ISSUE THREAD

**Issue by jsonbecker** [mrkaye97/slackr#5]
I get the same error each time I use `dev.slackr` or `ggslackr` etc:

```
Error in data.frame(id = x$id, name = x$name, real_name = x$real_name) : 
  arguments imply differing number of rows: 1, 0
```

**Comment by hrbrmstr** [comment]
Try using the most current github version. Those should be fixed.

**Comment by LDalby** [comment]
Using the latest version (1.2.2) I get:
`Error in`[<-.data.table`(x, j = name, value = value) : 
  Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though.`

when calling `dev.slackr` with the qplot example. 

Any hints on how to solve it?

-Lars

**Comment by yanlesin** [comment]
@LDalby I got this error resolved (even in CRAN version 1.2) when `api_token` configuration string had proper API token, not just `token` configuration string...

**Comment by LDalby** [comment]
@yanlesin Hmm, I am using a full `API_token` as far as I can see. I call `slackrSetup(api_token = "xxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxx")` (the xs being my real token of course) before calling `ggslackr(qplot(mpg, wt, data=mtcars))`. But I still get the error. Strange.

**Comment by hrbrmstr** [comment]
(have not abandoned the package…should have time to address these this week)

**Comment by LDalby** [comment]
Good to hear!

Let me know if you want some help testing.

-Lars

**Comment by LDalby** [comment]
As of version `1.2.3` this issue was solved for me.

Thanks
Lars
